kind: Service
metadata:
  name: alex-svc
spec:
  type: ClusterIP
  selector:
    app: alex
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: webapp
---
kind: StatefulSet
metadata:
  name: alex
  labels:
    app: alex
spec:
  selector:
    matchLabels:
      app: alex
  securityContext:
    runAsUser: kortical
  replicas: 1
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: alex
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: alex
          image: eu.gcr.io/kortical-goodloans/alex:v1
          imagePullPolicy: Always
          command: [ "run-cmd.sh" ]
          args: [ "uwsgi",
                  "--lazy-apps",
                  "--master",
                  "--http", ":5000",
                  "--http-keepalive",
                  "--http-timeout", "1800000",
                  "--die-on-term",
                  "--buffer-size", "32768",
                  "--reload-on-rss", "4096",
                  "--mount", "/=alex.main:app",
                  "--wsgi-disable-file-wrapper",
                  "--enable-threads", ]
          ports:
            - containerPort: 5000
              name: webapp
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: webapp
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 4
            failureThreshold: 30
            periodSeconds: 5
